name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test Resignal using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 如需指定 Xcode 版本，可加一个步骤使用 setup-xcode Action（可选）
      # - name: Select Xcode version
      #   uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: "16.0"

      - name: Build
        env:
          scheme: Resignal        # 这里改成你在 Xcode 里看到的实际 Scheme 名
          platform: iOS Simulator
        run: |
          cd Resignal-iOS
          # xcrun xctrace returns via stderr, not the expected stdout
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          xcodebuild \
            build-for-testing \
            -scheme "$scheme" \
            -project Resignal.xcodeproj \
            -destination "platform=$platform,name=$device"

      # - name: Test
      #   env:
      #     scheme: Resignal
      #     platform: iOS Simulator
      #   run: |
      #     cd Resignal-iOS
      #     # xcrun xctrace returns via stderr, not the expected stdout
      #     device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
      #     xcodebuild \
      #       test-without-building \
      #       -scheme "$scheme" \
      #       -project Resignal.xcodeproj \
      #       -destination "platform=$platform,name=$device"
